name: deploy on push production branch
on:
  push:
    branches:
      - prod

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v4

      - name: install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: deploy to prod server
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key
          chmod 600 private_key
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key -p ${{ secrets.SSH_PORT }}" \
            ./html/ ${{ secrets.SSH_USER_NAME }}@${{ secrets.PROD_HOST }}:/var/www/prod-site/